### ISSUE TITLE
january appears as "00" instead of "01"

### ISSUE THREAD

**Issue by Shiroe93** [stefmde/HomeAssistantSimpleDateTimeClockCard#1]
the month of january appears as 0 instead of 1 
also the card is not in hacs default as you claim i had to install it manually 

card config:

type: custom:simple-date-time-clock-card
date_locale: it
time_font_size: 2rem
date_font_size: 1rem
date_months_lead_zero: true
date_separator_char: /
date_year_two_digit: true

result 
![immagine](https://github.com/stefmde/HomeAssistant-SimpleDateTimeClockCard/assets/56954468/a384011d-a028-4050-8852-6149cce87514)

any idea why?

lastly i wanted to ask if it is possible to have the date on top and the clock on the bottom

**Comment by stefmde** [comment]
Hi thanks for your report but sadly I can't report that with your config. But I think that the `date_locale` should be` it-IT`. Except that it may not be needed at all. But on my side it shows the correct date and time with `it`, `it-IT` or without that property.
I created a pull request for HACS so that the integrate my repo but they claimed that it is not compatible with HA which is bullshit because it works since months in my HA but they never explained what the problem is so I don't want to waste energy on that. But I will change that badge.

**Comment by Shiroe93** [comment]
i solved the  issue by adding +1  at the m variable

________________________________
Da: Stefan Müller (StefmDE) ***@***.***>
Inviato: domenica 11 febbraio 2024 14:08
A: stefmde/HomeAssistant-SimpleDateTimeClockCard ***@***.***>
Cc: Shiroe93 ***@***.***>; Author ***@***.***>
Oggetto: Re: [stefmde/HomeAssistant-SimpleDateTimeClockCard] january appears as "00" instead of "01" (Issue #1)


Hi thanks for your report but sadly I can't report that with your config. But I think that the date_locale should be it-IT. Except that it may not be needed at all. But on my side it shows the correct date and time with it, it-IT or without that property.
I created a pull request for HACS so that the integrate my repo but they claimed that it is not compatible with HA which is bullshit because it works since months in my HA but they never explained what the problem is so I don't want to waste energy on that. But I will change that badge.
